import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/header/header";

import { ToastContainer } from 'react-toastify';

import 'react-toastify/dist/ReactToastify.css';
import Footer from "@/components/footer/footer";
import Layout from "./dashboard/layout";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

{/* <Layout>
  <Page></Page> login
  <Page></Page> dashboard
</Layout> */}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href= "https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" />
        <script async src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"></script>
        <script async src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" ></script>
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        
        <Header></Header>

        {/* yahan page.js */}
        {children}

        <ToastContainer />

        <Footer></Footer>
      </body>
    </html>
  );
}
